name: kubernetes-demo-infra-deployment-pipeline
run-name: Kubernetes Demo Infra Deployment Pipeline
on:
  push:
    branches:
      - master

permissions:
      id-token: write
      contents: read

env:
  tf_version: '1.10.4'
  tg_version: '0.67.0'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{secrets.ASSUME_ROLE}}
          role-session-name: aws-github-session

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_command: 'run-all apply'